version: '3.2'

services:

  dcmrecv:
    image: qiicr/docker-dcmtk-cli
    container_name: dcmrecv
    volumes:
      - .:/data/
    ports:
      - 8083:8083
    command: dcmrecv -od /data/dicom-dcmrecv/storage --verbose 8083 --config-file /data/dicom-dcmrecv/storescp.cfg  default

  dicom_api_app: &app
    build:
      context: .
      args:
        requirements: requirements/development.txt
    container_name: dicom_api
    environment:
      # use in code
      - DEBUG=True
      - SETTINGS_FILE=api.dev.yml
    restart: always
    volumes:
      - .:/app:delegated
    ports:
      - 8080:8080
      - 8081:8081
    command: make adev
#
#  test:
#    <<: *app
#    container_name: dicom_api_test
#    ports:
#      - 8082:8082
#    command: make _test

