apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dicom-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dicom-api
    spec:
      containers:
      - args:
        - python3
        - -m
        - dicom_api
        env:
        - name: SETTINGS_FILE
          value: api.prod.yml
        image: truskovskyi/dcmrecv_api:latest
        name: dicom-api
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /data/dicom-dcmrecv/storage
          name: dcmrecv-storage
      restartPolicy: Always
      volumes:
      - name: dcmrecv-storage
        nfs:
          server: 10.27.242.105
          path: "/"

